### ISSUE TITLE
Multiple pfSense?

### ISSUE THREAD

**Issue by gabrielpc1190** [hannah98/pfsense-backup#1]
I manage 10+ pfsense, and I would like to be able to backup them on a daily basis.
Is there a way to use this container to backup multiple pfSense boxes?
I mean without using multiple containers

**Comment by hannah98** [comment]
I will look into this!

**Comment by gabrielpc1190** [comment]
No need to progress on this.
Now autobackup is free for all pfSense 2.4.4 users!
https://www.netgate.com/docs/pfsense/backup/autoconfigbackup.html
